Add foundational support for API key expiration (#5341)
* add expires_at column

* update query

* add .sqlx

* update all call sites

* integrate with CLI

* update docstring

* log the expiration date

* clear out stale commented code

* add basic test

* add Expired to AuthResult

* update check_key to factor in expires_at

* Update internal/tensorzero-auth/src/postgres/mod.rs

* extend create-with-expiration test to confirm post-creation auth result

* accept 0 args for --create-api-key

* test that created key does not have expires_at set

* clarify test expiration time intent

* document

* regenerate node API

* fix typo

* explicitly pass in the string in test

* docs

* rename enum variants

* define --expiration that requires --create-api-key

* update test

* add new test for invalid (in the past) --expiration value

* Apply suggestion from @jinnovation

* split --expiration into separate arg group

```
> ./target/debug/gateway --expiration "2025-12-20 23:00:00.000000 UTC"
error: the following required arguments were not provided:
  --create-api-key
```

```
> ./target/debug/gateway --create-api-key --expiration "2025-12-20 23:00:00.000000 UTC"
2025-12-30T00:34:59.998179Z ERROR gateway: Failed to create API key: Expiration datetime needs to be in the future
```

* update tests

* docstring

* more docstring

* collapse conditional

* update test w/ now + 2s

* Fix

* Fix

* Fix

---------

Co-authored-by: Gabriel Bianconi <1275491+GabrielBianconi@users.noreply.github.com>