split --expiration into separate arg group
```
> ./target/debug/gateway --expiration "2025-12-20 23:00:00.000000 UTC"
error: the following required arguments were not provided:
  --create-api-key
```

```
> ./target/debug/gateway --create-api-key --expiration "2025-12-20 23:00:00.000000 UTC"
2025-12-30T00:34:59.998179Z ERROR gateway: Failed to create API key: Expiration datetime needs to be in the future
```